### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by srix55** [cachapa/tudo_client#21]
I am running flutter on Fedora 64 bit. 
Not sure what I'm doing wrong right now. I had to upgrade the hive dependency as mentioned in the other issue.

- I run the server. Server runs fine at 0.0.0.0:8080 (Able to see empty map in browser)
- I run the client. Client UI is fine - no widget errors. But shows the red offline bar at the bottom.
- I am connecting to `wss://0.0.0.0:8080` (changed in config)

However, on printing the error in connection, I see this.

```js
flutter: disconnected: WebSocketChannelException: WebSocketChannelException: HandshakeException: Connection terminated during handshake: #0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:98:24)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _rootRunBinary (dart:async/zone.dart:1378:47)
#5      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#10     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#11     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#12     _rootRunBinary (dart:async/zone.dart:1378:47)
#13     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#18     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#19     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#20     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:166:18)
#21     _rootRunBinary (dart:async/zone.dart:1378:47)
#22     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#23     _FutureListener.handleError (dart:async/future_impl.dart:169:20)
#24     Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
#25     Future._propagateToListeners (dart:async/future_impl.dart:740:24)
#26     Future._completeError (dart:async/future_impl.dart:550:5)
#27     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:606:7)
#28     _rootRun (dart:async/zone.dart:1354:13)
#29     _CustomZone.run (dart:async/zone.dart:1258:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by srix55** [comment]
Aaah... able to get it to work by not having the server run locally... instead kept the server address unchanged. Thanks for a clear demo :+1:  Closing the issue.

**Comment by cachapa** [comment]
Hey, thanks for experimenting. To be honest I pushed the production server by mistake, so please don't use it other than for very light testing.

The reason you couldn't connect to your local server is most likely because you're using `wss://` which is the secure socket version, which your local server probably isn't configured for.

Try `ws://0.0.0.0:8080` instead.

Please note that I'll probably close down access to the production server with a key soon, so your client might stop working if you continue pointing it there.

**Comment by srix55** [comment]
You're right. I changed wss to ws and it's connecting to my local server as expected. Thanks.
